language: go
go:
- 1.11.x
services:
  - docker
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.12.1
script:
  - $GOPATH/bin/golangci-lint run ./...
  - go test -race -cover
