image: golang
pipelines:
  default:
    - step:
        name: Setup
        script:
          - mkdir -p /go/src/bitbucket.org/atlassian/transport
          - cp -R ./* /go/src/bitbucket.org/atlassian/transport
    - step:
        name: Lint
        script:
          - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.9.1
          - $GOPATH/bin/golangci-lint run ./...
    - step:
        name: Test
        script:
          - echo '# Generate coverage report and test for race conditions'
          - go test -race -cover
